orbs:
  node: circleci/node@4.0.0
version: 2.1
jobs:
  test-node-10:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '10'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-jest-jasmine:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages: *install
      - run:
          command: JEST_JASMINE=1 yarn test-ci-partial && JEST_JASMINE=1 yarn test-leak
      - store_test_results:
          path: reports/junit

  test-node-12:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '12'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-14:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '14'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-node-15:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '15'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-or-deploy-website:
    working_directory: ~/jest
    executor: node/default
    resource_class: large
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages: *install
      - run:
          name: Test or Deploy Jest Website
          command: ./.circleci/website.sh