# version: 2.1
# orbs:
#   welcome: circleci/welcome-orb@0.4.1

# workflows:
#   welcome:
#     jobs:
#       - welcome/run


version: 2.1
jobs:
  build:
    working_directory: ~/public
    docker:
      - image: circleci/node:12.x
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
