# version: 2.1
# orbs:
#   welcome: circleci/welcome-orb@0.4.1

# workflows:
#   welcome:
#     jobs:
#       - welcome/run

version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build